# Generated by Django 2.2.12 on 2020-05-14 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('species', models.CharField(max_length=200)),
                ('genus', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='static/images/')),
                ('image_title', models.TextField()),
                ('family', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('uses', models.TextField()),
            ],
        ),
    ]
