# Generated by Django 2.2.12 on 2020-05-14 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='image',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='image_title',
        ),
        migrations.AddField(
            model_name='plant',
            name='image1',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='static/images/'),
        ),
        migrations.AddField(
            model_name='plant',
            name='image1_title',
            field=models.CharField(blank=True, default=None, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='image2',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='static/images/'),
        ),
        migrations.AddField(
            model_name='plant',
            name='image2_title',
            field=models.CharField(blank=True, default=None, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='image3',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='static/images/'),
        ),
        migrations.AddField(
            model_name='plant',
            name='image3_title',
            field=models.CharField(blank=True, default=None, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='image4',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='static/images/'),
        ),
        migrations.AddField(
            model_name='plant',
            name='image4_title',
            field=models.CharField(blank=True, default=None, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='image5',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='static/images/'),
        ),
        migrations.AddField(
            model_name='plant',
            name='image5_title',
            field=models.CharField(blank=True, default=None, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='image6',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='static/images/'),
        ),
        migrations.AddField(
            model_name='plant',
            name='image6_title',
            field=models.CharField(blank=True, default=None, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='uses',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
