# Generated by Django 2.2.12 on 2020-05-14 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0002_auto_20200514_1457'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='image1',
            new_name='image_alternate1',
        ),
        migrations.RenameField(
            model_name='plant',
            old_name='image1_title',
            new_name='image_alternate1_title',
        ),
        migrations.RenameField(
            model_name='plant',
            old_name='image2',
            new_name='image_alternate2',
        ),
        migrations.RenameField(
            model_name='plant',
            old_name='image2_title',
            new_name='image_alternate2_title',
        ),
        migrations.RenameField(
            model_name='plant',
            old_name='image3',
            new_name='image_flower',
        ),
        migrations.RenameField(
            model_name='plant',
            old_name='image3_title',
            new_name='image_flower_title',
        ),
        migrations.RenameField(
            model_name='plant',
            old_name='image4',
            new_name='image_fruit',
        ),
        migrations.RenameField(
            model_name='plant',
            old_name='image4_title',
            new_name='image_fruit_title',
        ),
        migrations.RenameField(
            model_name='plant',
            old_name='image5',
            new_name='image_leaf',
        ),
        migrations.RenameField(
            model_name='plant',
            old_name='image5_title',
            new_name='image_leaf_title',
        ),
        migrations.RenameField(
            model_name='plant',
            old_name='image6',
            new_name='image_whole',
        ),
        migrations.RenameField(
            model_name='plant',
            old_name='image6_title',
            new_name='image_whole_title',
        ),
    ]
