# Generated by Django 2.2.12 on 2020-05-17 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0003_auto_20200514_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='status',
            field=models.CharField(default='Non-native', max_length=25),
            preserve_default=False,
        ),
    ]
