# Generated by Django 2.2.12 on 2020-05-20 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0004_plant_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='uses',
            new_name='food_uses',
        ),
        migrations.AddField(
            model_name='plant',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='medicinal_uses',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
