# Generated by Django 2.2.12 on 2020-05-20 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0005_auto_20200520_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='other_uses',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
