# Generated by Django 2.2.12 on 2020-05-24 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0006_plant_other_uses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='other_uses',
            field=models.TextField(default=None),
        ),
    ]
