# Generated by Django 2.2.12 on 2020-05-24 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0009_auto_20200523_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
