# Generated by Django 2.2.12 on 2020-09-14 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0010_plant_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='image_alternate1',
            field=models.CharField(blank=True, default=None, max_length=2090, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='image_alternate2',
            field=models.CharField(blank=True, default=None, max_length=2090, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='image_flower',
            field=models.CharField(blank=True, default=None, max_length=2090, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='image_fruit',
            field=models.CharField(blank=True, default=None, max_length=2090, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='image_leaf',
            field=models.CharField(blank=True, default=None, max_length=2090, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='image_whole',
            field=models.CharField(blank=True, default=None, max_length=2090, null=True),
        ),
    ]
